In [1]:
%load_ext autoreload
%autoreload 2

# Quantity and Unit
*Text*

Text here

In [2]:
import pyunitwizard as puw
puw.configure.load_libraries(['pint', 'simtk.unit'])

In [3]:
var = puw.quantity(value=3.0, unit='joules', form = 'pint')
var

3.0 <Unit('joule')>

In [4]:
var = puw.quantity([0,1,2], 'angstroms', 'pint')
var

array([0, 1, 2]) <Unit('angstrom')>

In [5]:
print(var)

[0 1 2] angstrom


In [6]:
var = puw.quantity(1, 'Å', 'pint')

In [7]:
var

1 <Unit('angstrom')>

In [8]:
import numpy as np
var = puw.quantity(np.zeros(shape=[2,6,3]), 'angstroms', 'Pint')
var

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]]) <Unit('angstrom')>

In [9]:
puw.string_to_quantity('10.0 Å')

10.0 <Unit('angstrom')>

In [10]:
puw.string_to_quantity('1.0 mol/L')

1.0 <Unit('mole / liter')>